#Resource Icon, 1, ".\GFX\appointment-new-2.ico"
#Resource Manifest, 1, "IsIt.exe.manifest"

#Resource VersionInfo
#Resource FileVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0
#Resource ProductVersion %VERSION_MAJOR, %VERSION_MINOR, %VERSION_REVISION, 0

#Resource StringInfo "0407", "04B0"

#Resource Version$ "CompanyName",      "BasicAware"
#Resource Version$ "FileDescription",  "Evaluate date/time values"
#Resource Version$ "LegalCopyright",   "Copyright 2022 BasicAware"
#Resource Version$ "OriginalFilename", "IsIt.exe"
#Resource Version$ "ProductName",      "IsIt"
#Resource Version$ "ProductVersion",   "1.0.0.0"
#Resource Version$ "FileVersion",      "1.0.0.0"
#Resource Version$ "Comments",         "Written by Knuth Konrad"

$COMPANY_NAME = "BasicAware"
